### ISSUE TITLE
Привет, please бро перемести MIK.exe в bin

### ISSUE THREAD

**Issue by BlackCatDevel0per** [CryptoNickSoft/MIK#1]
У меня прога не запустилась пока не переместил в bin, а так спасибо =D

**Comment by CryptoNickSoft** [comment]
это оттого что нет звука в вашам устройстве

вс, 24 июл. 2022 г. в 15:58, Asadbek Sayfiev ***@***.***>:

**Comment by Thiagopb35** [comment]
Здравствуйте, как мне получить доступ к исходному коду mik 4.0, чтобы узнать, можно ли его разработать для системы Mac OS?

**Comment by CryptoNickSoft** [comment]
Программа использует WinAPI, без серьёзных переделок нигде кроме Windows не
запустится.
Легче с нуля писать по образу и подобию.

сб, 25 нояб. 2023 г. в 08:13, Thiagopb35 ***@***.***>:

**Comment by Thiagopb35** [comment]
вы не заинтересованы в разработке этого программного обеспечения для Mac OS, в отличие от других, с которыми мне нужно работать, поскольку я работаю с ТВ-боксами, я составлю список инструментов, хорошо.

для ТВ-бокса Amlogic..... инструменты для записи USB 2.2.0 инструменты записи amlogic 3.2.0 инструменты настройки 2.0.10 инструменты амлогик 7.1.0 создатель карточек записи USB-инструмент для обновления Amlogic Pulse amlScankey_tool

тв приставка рокчип WNpctool Rockchip FactoryTool 1.64 инструмент для ванны Rockchip 1.8 Rockchip создает инструмент обновления диска 1.53 ркдампер 108 помощник водителя 4.5 инструменты Android 2.38 обновитьDlltool

телевизионная приставка Alwiiner феникс USB про 4.0.0 костюм феникса 1.10 карта феникса 4.2.4

создание прошивки mik 4.0 —> мультиизображительная кухня АЭС 8.1.4
