### ISSUE TITLE
kernel command linei in reconsructed  boot.img 

### ISSUE THREAD

**Issue by seyko2** [CryptoNickSoft/MIK#3]
In reconsructed boot.img for Android (win7 x64) command line is compressed by cpio (or other tool).In original boot.img it is not. Resulted umage is unusefull.

**Comment by CryptoNickSoft** [comment]
да пох...

пн, 2 сент. 2024 г. в 20:32, seyko2 ***@***.***>:

**Comment by seyko2** [comment]
Wonddefull.I"m go to testing
