### ISSUE TITLE
Cant buuld vendor.img separately. Only when building super.img with options on in settings

### ISSUE THREAD

**Issue by seyko2** [CryptoNickSoft/MIK#4]
Why program cant build system, vendor, product by separte step (not whitin building super.img).

 And second: very big time need to construct super.img (classic hard disk, no ssd). It looks that size of buffer for copying is very small

**Comment by CryptoNickSoft** [comment]
ин нах

пн, 2 сент. 2024 г. в 20:50, seyko2 ***@***.***>:
